blank_issues_enabled: false 
contact: false 

templates:
  - name: "Project Suggestion"
    description: "Propose an idea for a new project."
    title: "Project Suggestion Title"
    labels: ["Project Suggestion"]
  
  - name: "Bug Report"
    description: "Report a bug or issue."
    title: "Bug Report Title"
    labels: ["bug", "help wanted"]
  
  - name: "Feature Request"
    description: "Request a new feature or enhancement."
    title: "Feature Request Title"
    labels: ["feature", "enhancement"]

  - name: "Other"
    description: "Use this template for any other issues or inquiries."
    title: "Other Issue Title"
    labels: ["question", "others"]

choose_template:
  title: "Choose an Issue Template"
  description: "Please select one of the templates below to create your issue."
